### ISSUE TITLE
Error when loading game

### ISSUE THREAD

**Issue by alfarisi13** [Jimmyokok/RentControl#1]
Failure has occurred while loading a type.
TypeLoadException: Failure has occurred while loading a type.
  at Unity.Jobs.IJobExtensions+JobStruct`1[T].Execute (T& data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x00001] in <a8fc136049044b19982b5abcb6f6b426>:0 
  at (wrapper delegate-invoke) Unity.Jobs.IJobExtensions+JobStruct`1+ExecuteJobFunction[RentControl.Systems.CustomGarbageTruckAISystem+GarbageActionJob].invoke_void_T&_intptr_intptr_JobRanges&_int(RentControl.Systems.CustomGarbageTruckAISystem/GarbageActionJob&,intptr,intptr,Unity.Jobs.LowLevel.Unsafe.JobRanges&,int)
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Jimmyokok** [comment]
Do you have the mod ImprovedServiceVehicleAI installed?

**Comment by alfarisi13** [comment]
I had the mod installed first. After the first error, I've tried removing that mod, but the problem persists

**Comment by Jimmyokok** [comment]
This should never happen. I will help you to deal with this problem and I have some suggestions for you. Have you:

- (1). Checked your game version? Is it 1.0.15f1 or some other version?
- (2). Remove both RentControl and ImprovedServiceVehicleAI, then try to load a save before you install RentControl?
- (3). Remove ImprovedServiceVehicleAI while keeping RentControl, and start a new city?

If (1) go wrong, I believe I can't help you in this case.
If (2) go wrong, it is evident that ImprovedServiceVehicleAI is save-breaking by making saves unable to load without that mod.
If (3) go wrong, RentControl is broken and please provide your BepInEx version so I can fix it.
If everything goes well, please provide your BepInEx version and the list of mods you are going to use with this mod.

**Comment by alfarisi13** [comment]
ok, so apparently the problem is on my side.

I've had run it with only RentControl installed, and it still crash. and apparently I was still running on game version 1.0.13

I've upgraded it and it works nicely.

MODLIST:
BepInEx v5.4.22.0
RentControl
ImprovedServiceVehicleAI
HookUI
ExtendedTooltip
DucksInARow
UnemploymentMonitor
